# Generated by Django 5.1.7 on 2025-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customworker',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='customworker',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customworker',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customworker',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='customworker',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
