# Generated by Django 5.1.7 on 2025-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_customworker_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customworker',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
